services:
  db:
    image: postgres:16
    container_name: postgres_saai
    restart: always
    environment:
      POSTGRES_USER: saai
      POSTGRES_PASSWORD: saai
      POSTGRES_DB: saai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: saai
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db


volumes:
  pgdata:
