services:
  db:
    image: postgres:16
    container_name: postgres_saai
    restart: always
    environment:
      POSTGRES_USER: saai
      POSTGRES_PASSWORD: saai
      POSTGRES_DB: saai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .              # raiz do projeto
      dockerfile: backend/Dockerfile
    container_name: saai
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  pgdata:
